---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: terraform
    directory: /modules/kms/
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: terraform
    directory: /modules/ec2/
    schedule:
      interval: daily
    open-pull-requests-limit: 10
