# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /modules/kms/
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /modules/ec2/
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /envs/dev/kms/
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /envs/dev/s3/
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /envs/dev/vpc/
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /envs/dev/subnet/
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /envs/dev/nat/
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /envs/dev/vpce/
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /envs/dev/ssm/
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /envs/dev/ec2/
    schedule:
      interval: daily
