---
AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket and DynamoDB table for Terraform
Parameters:
  ResourcePrefix:
    Description: Set the resource prefix.
    Type: String
    Default: tfstate
Resources:
  TerraformStateS3Bucket:
    Type: AWS::S3::Bucket
    # DeletionPolicy: Retain
    # UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub ${ResourcePrefix}-${AWS::Region}-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: Move-to-Intelligent-Tiering-after-0day
            Status: Enabled
            Transitions:
              - TransitionInDays: 0
                StorageClass: INTELLIGENT_TIERING
            NoncurrentVersionExpiration:
              NoncurrentDays: 1
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
      Tags:
        - Key: Name
          Value: !Sub ${ResourcePrefix}-${AWS::Region}-${AWS::AccountId}
        - Key: Application
          Value: Terraform
  TerraformLockDynamodbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ResourcePrefix}-lock
      TableClass: STANDARD
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      ContributorInsightsSpecification:
        Enabled: false
      DeletionProtectionEnabled: false
      SSESpecification:
        SSEEnabled: false
      TimeToLiveSpecification:
        Enabled: false
      Tags:
        - Key: Name
          Value: !Sub ${ResourcePrefix}-lock
        - Key: Application
          Value: Terraform
Outputs:
  TerraformStateS3Bucket:
    Value: !Ref TerraformStateS3Bucket
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-TerraformStateS3Bucket
  TerraformLockDynamodbTable:
    Value: !Ref TerraformLockDynamodbTable
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-TerraformLockDynamodbTable
