---
name: CI workflows
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      workflow:
        required: true
        type: choice
        options:
          - lint-and-scan
          - format
          - upgrade
        description: Choose the workflow to run
        default: lint-and-scan
permissions:
  contents: write
  pull-requests: write
jobs:
  terraform-lint-and-scan:
    if: >
      github.event_name == 'push'
      || github.event_name == 'pull_request'
      || (github.event_name == 'workflow_dispatch' && inputs.workflow == 'lint-and-scan')
    uses: dceoy/gh-actions-for-devops/.github/workflows/terraform-lint-and-scan.yml@main
    with:
      search-path: .
      terraform-version: latest
      terragrunt-version: latest
  terraform-format:
    if: >
      github.event_name == 'pull_request'
      || (github.event_name == 'workflow_dispatch' && inputs.workflow == 'format')
    uses: dceoy/gh-actions-for-devops/.github/workflows/terraform-format-and-pr.yml@main
    with:
      search-path: .
      terraform-version: latest
      terragrunt-version: latest
  dependabot-terraform-lock-files-upgrade:
    if: >
      (github.event_name == 'pull_request' && startswith(github.head_ref, 'dependabot/terraform/'))
      || (github.event_name == 'workflow_dispatch' && inputs.workflow == 'upgrade')
    uses: dceoy/gh-actions-for-devops/.github/workflows/terraform-lock-files-upgrade.yml@main
    with:
      terraform-working-directory-to-version-tf-json: >
        {"envs/dev/ec2": "modules/ec2/version.tf",
         "envs/dev/kms": "modules/kms/version.tf",
         "envs/dev/nat": "modules/nat/version.tf",
         "envs/dev/s3": "modules/s3/version.tf",
         "envs/dev/ssm": "modules/ssm/version.tf",
         "envs/dev/subnet": "modules/subnet/version.tf",
         "envs/dev/vpc": "modules/vpc/version.tf",
         "envs/dev/vpce": "modules/vpce/version.tf"}
      terraform-version: latest
  dependabot-auto-merge:
    if: >
      github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    needs:
      - terraform-lint-and-scan
      - dependabot-terraform-lock-files-upgrade
    uses: dceoy/gh-actions-for-devops/.github/workflows/dependabot-auto-merge.yml@main
