---
name: CI workflows
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      workflow:
        required: true
        type: choice
        options:
          - lint-and-scan
          - format
        description: Choose the workflow to run
        default: lint-and-scan
permissions:
  contents: write
  pull-requests: write
jobs:
  terraform-lint-and-scan:
    if: >
      github.event_name == 'push'
      || github.event_name == 'pull_request'
      || (github.event_name == 'workflow_dispatch' && inputs.workflow == 'lint-and-scan')
    uses: dceoy/gh-actions-for-devops/.github/workflows/terraform-lint-and-scan.yml@main
    with:
      search-path: .
      terraform-version: latest
      terragrunt-version: latest
  terraform-format:
    if: >
      github.event_name == 'pull_request'
      || (github.event_name == 'workflow_dispatch' && inputs.workflow == 'format')
    uses: dceoy/gh-actions-for-devops/.github/workflows/terraform-format-and-pr.yml@main
    with:
      search-path: .
      terraform-version: latest
      terragrunt-version: latest
  dependabot-auto-merge:
    if: >
      github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    needs:
      - terraform-lint-and-scan
    uses: dceoy/gh-actions-for-devops/.github/workflows/dependabot-auto-merge.yml@main
