---
name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install commands
        run: |
          python -m pip install --upgrade --no-cache-dir cfn-lint yamllint
          npm install -g jsonlint
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      - name: Execute jsonlint
        run: |
          find . -type f -name '*.json' \
            | xargs -t jsonlint -q
      - name: Execute yamllint
        run: |
          find . -type f -name '*.yml' -o -name '*.yaml' \
            | xargs -t yamllint -d '{"extends": "relaxed", "rules": {"line-length": "disable"}}'
      - name: Execute cfn-lint
        run: |
          find . -type f -name '*.cfn.yml' -o -name '*.cfn.yaml' \
            | xargs -t cfn-lint --template
      - name: Execute tflint
        run: |
          tflint --recursive
