---
name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: hashicorp/setup-terraform@v3
      - name: Install commands
        run: |
          python -m pip install --upgrade --no-cache-dir cfn-lint yamllint
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      - name: Execute yamllint
        run: |
          find . -type f -name '*.yml' -o -name '*.yaml' \
            | xargs -t yamllint -d '{"extends": "relaxed", "rules": {"line-length": "disable"}}'
      - name: Execute cfn-lint
        run: |
          find . -type f -name '*.cfn.yml' -o -name '*.cfn.yaml' \
            | xargs -t cfn-lint --template
      - name: Execute terraform fmt
        run: |
          terraform fmt -recursive -check
      - name: Execute tflint
        run: |
          tflint --recursive
      - name: Execute tfsec
        run: |
          tfsec .
